### ISSUE TITLE
Webapp stuck at "Loading" status.

### ISSUE THREAD

**Issue by Dummydud3** [Brikwerk/nxbt#124]
[NXBT Webapp.pdf](https://github.com/Brikwerk/nxbt/files/11545007/NXBT.Webapp.pdf)

Immedatly after selecting "Pro Controller", the app freezes with this "loading" status. The terminal gives no help whatsoever, and I plan to slide in a few debug scripts to see what the problem is, but this is still an issue for me. Thanks :pray:

**Comment by jdmagic** [comment]
Hey, so- same issue. Using your fork I got the webapp up and running but it gets stuck on loading. The test and demo scripts both work. Webapp doesn't, though. Any fix ?

**Comment by Dummydud3** [comment]
Unfortunately I havent gotten anything good from it. Waiting for news from the developer.

**Comment by Dummydud3** [comment]
I fixed it!

**Comment by jdmagic** [comment]
> I fixed it!

Hey, so, great news! This is awesome to hear because I was hoping to use this myself but I'm not competent enough to work on this sort of project myself. I assume that Brikwerk's original branch isn't updated yet, but you've made pull requests? Should I be using your branch called `FIXED-WEBAPP` for now? Thanks in advance!!
