### ISSUE TITLE
AF_BLUETOOTH ?????

### ISSUE THREAD

**Issue by monkeybee11** [Brikwerk/nxbt#135]
ello monkey is trying to run this on my raspberry pi4 but when trying to run the demo im getting this 

`pi@raspberrypi:~ $ sudo nxbt demo
Running Demo...
An error occurred while running the demo:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nxbt/controller/server.py", line 96, in run
    itr, ctrl = self.connect()
  File "/usr/lib/python3.10/site-packages/nxbt/controller/server.py", line 352, in connect
    family=socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
` 

doing some googlering to try and find out whats wrong found this script to see if bluetooth socket is enabled and it comes back with yes

`import socket

if hasattr(socket, 'AF_BLUETOOTH'):
    print('Bluetooth support is available')
else:
    print('Bluetooth support is not available')`
so dont know y its not working :( sry im still new to python and code stuff

**Comment by Brikwerk** [comment]
Unfortunately, I'm not able to reproduce this issue with a fresh copy of the latest 32bit Raspberry Pi OS on an RPi 4.

One thing I'm seeing in your traceback is that you're using Python 3.10. From my testing, this doesn't come standard in the current RPi OS image. Did you install 3.10 yourself? If so, you might have installed a copy that wasn't compiled with Bluetooth support.

Additionally, how are you running the test for Bluetooth support? Are you running something like `python test.py` or `sudo python test.py`?

**Comment by monkeybee11** [comment]
errr open the test.py in geany(my ide of choice on the pi bc coudnt find out how to update python for thorny)
 then click run (im really new to non windowsOS im mainly a windows boy so using CMD is not natrual for me aside form "pip install .......")
 
 forgot to say in my op but im dislexic so very sry for any bad spelling
 
yes ive installed python my self fallowing some guides online bc im hosting a discord bot on my pi and well had to update python to keep inspec for pycord

ATM after posting that error report ive upgraded to 3.11.4 fallowing a diffront guide but when running `sudo nxbt test` or `sudo nxbt demo` get the same error still saying python3.10 YET when running `python --version` it says im using verion 3.11.4 so >.< is it posable ive royaly messed something up

sry for late reply didt see it till now

**Comment by Brikwerk** [comment]
Alright, my hunch is that Geany is using the original Python 3.9 installation while the command line has been configured to use the Python version you installed. Basically, you've got multiple versions of Python available on your Pi but only 3.9 has been compiled for Bluetooth use.

NXBT will still say it's using 3.10 since it was installed on this version. You need to manually uninstall NXBT on Python 3.10 before you can reinstall on 3.11. Since you've configured your system to point to 3.11, you need to manually invoke 3.10's pip with something along the following lines: `python3.10 -m pip uninstall nxbt`.

For a solution, I would recommend that you swap back to the 3.9 version with Bluetooth support. Pycord, from what I'm reading, supports Python 3.8+, so you should have no issues supporting your Discord bot on the original Python version supplied by RPi OS. You can check which versions of Python a package supports (most of the time) by looking on the Python Package Index: https://pypi.org/project/py-cord/ (the versions supported are under the classifiers section on the left sidebar).

And no worries about spelling or otherwise ;) Welcome to the Linux community.

**Comment by monkeybee11** [comment]
ye monkey has mannaged to fix it on 3.11

had to use both `python3.10 -m pip uninstall nxbt`
and `sudo pip uninstall nxbt` to remove NXBT

then ran 
`sudo apt-get update`

`sudo apt-get install bluetooth bluez libbluetooth-dev`

`sudo python3.11 -m pip install pybluez`

then `sudo pip3.11 install nxbt`

and now everything is all good and working :)

**Comment by Coder31716** [comment]
Hi

**Comment by Coder31716** [comment]
What is client1 trying to say??
I didn't understand
