### ISSUE TITLE
Is it possible to run on android?

### ISSUE THREAD

**Issue by Moyck** [Brikwerk/nxbt#50]
Thanks for this great library，I want to know can it run on Android?

**Comment by Brikwerk** [comment]
Unfortunately, NXBT is built around Linux-based Bluetooth APIs that largely aren't available on Android. There *might* be a possibility to get it working through Termux/Python-for-Android, however, this would likely require a major rewrite of NXBT. At this point, doing so isn't feasible due to the time commitment and Android knowledge necessary on my part.

Sorry if this wasn't the answer you were looking for. Thanks for your interest in the project, nonetheless.
